### PR TITLE
Finish user search endpoint

### PR DESCRIPTION
**Pull request by danielcrookall**
Created user search endpoint. 

http://localhost:5000/api/users  will return a list of all users (I chose to include all the details of the user from the database because I think it will be useful in the future). Query parameters can be specified to allow searching for any number of usernames.

Tested with postman. Examples below:

**no filtering (all users returned)**
image

**filtering by multiple usernames:**
image

username does not exist:
image

### CODE REVIEW

**Review by swongg — APPROVED** [review]
LGTM 💯 Thanks for putting this together so quickly. The searching also works for partial search queries right? i.e. typing 'ste' would gives me a result of 'steven' if that username exists

**Comment by swongg** [comment]
> LGTM 💯 Thanks for putting this together so quickly. The searching also works for partial search queries right? i.e. typing 'ste' would gives me a result of 'steven' if that username exists

 Could we also add a query param for retrieving exact matches? i.e. if exact=true, search query banana123 should return the user by the name banana123 and not return banana12345. I dont know if mongoose allows for this

**Comment by swongg** [comment]
Could we also add a query param for retrieving exact matches? i.e. if exact=true, search query banana123 should return the user by the name banana123 and not return banana12345. I dont know if mongoose allows for this

**Comment by danielcrookall** [comment]
> LGTM 💯 Thanks for putting this together so quickly. The searching also works for partial search queries right? i.e. typing `ste` would gives me a result of `steven` if that username exists

How it currently is, it only returns exact matches. So ste won't return steven.

**Comment by swongg** [comment]
> > LGTM 💯 Thanks for putting this together so quickly. The searching also works for partial search queries right? i.e. typing `ste` would gives me a result of `steven` if that username exists
> 
> How it currently is, it only returns exact matches. So ste won't return steven.
> 
> I'm no expert, but I don't think it makes sense to do partial searches on the backend like that. If you want to have an autocomplete feature where a user can type in part of a name and get the results, it would look like a search bar with a data list https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist
> 
> The data list would be filled with all the users from the database and the suggestions are automatic. But maybe you have something else in mind !

I didn't look at this into detail but would this work: https://www.mongodb.com/docs/atlas/atlas-search/autocomplete/#std-label-autocomplete-ref

**Review by Lakshya021 — APPROVED** [review]

**Pull request merged**
